homepage: "https://github.com/andrewilly/TARC"
language: c++
primary_contact: "andrerizzo@users.noreply.github.com"
auto_ccs:
  - "andrerizzo@users.noreply.github.com"
sanitizers:
  - address
  - undefined
architectures:
  - x86_64
  - i386
main_repo: "https://github.com/andrewilly/TARC.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
